FROM python:3.8

# 安装系统依赖
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0

RUN mkdir -p /app/backend && chmod 777 /app/backend

WORKDIR /app

# 复制需求文件并安装 Python 依赖
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 复制后端代码
COPY backend /app

# 暴露端口
EXPOSE 5000

# 运行应用
CMD ["python3", "app.py"]